"""empty message

Revision ID: 7a6b6053a6f2
Revises: 029268cbb078
Create Date: 2021-01-11 16:37:56.626054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6b6053a6f2'
down_revision = '029268cbb078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gb_account',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('user_nm', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=255), nullable=True),
    sa.Column('pw', sa.String(length=255), nullable=True),
    sa.Column('cdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('gb_meta_sim',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('smov_id', sa.String(length=255), nullable=False),
    sa.Column('rmov_id', sa.String(length=255), nullable=False),
    sa.Column('meta_sim', sa.Integer(), nullable=True),
    sa.Column('sim_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('gb_mov',
    sa.Column('mov_id', sa.Integer(), nullable=False),
    sa.Column('mov_prov', sa.String(length=255), nullable=True),
    sa.Column('mov_prov_id', sa.String(length=255), nullable=True),
    sa.Column('mov_title', sa.String(length=255), nullable=True),
    sa.Column('mov_owner', sa.String(length=255), nullable=True),
    sa.Column('mov_date', sa.String(length=10), nullable=True),
    sa.Column('mov_view_cnt', sa.BigInteger(), nullable=True),
    sa.Column('mov_tag', sa.Text(), nullable=True),
    sa.Column('mov_desc', sa.Text(), nullable=True),
    sa.Column('cdate', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('mov_id')
    )
    op.create_table('gb_mov_sim',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('smov_id', sa.String(length=255), nullable=False),
    sa.Column('rmov_id', sa.String(length=255), nullable=False),
    sa.Column('smov_start_sec', sa.Integer(), nullable=True),
    sa.Column('smov_end_sec', sa.Integer(), nullable=True),
    sa.Column('rmov_start_sec', sa.Integer(), nullable=True),
    sa.Column('rmov_end_sec', sa.Integer(), nullable=True),
    sa.Column('cdate', sa.DateTime(), nullable=True),
    sa.Column('mov_sim', sa.Integer(), nullable=True),
    sa.Column('sim_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('gb_search_lists',
    sa.Column('work_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=255), nullable=False),
    sa.Column('use_yn', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_table('gb_works',
    sa.Column('work_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.String(length=255), nullable=True),
    sa.Column('work_nm', sa.String(length=255), nullable=True),
    sa.Column('smov_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('cdate', sa.DateTime(), nullable=True),
    sa.Column('fdate', sa.DateTime(), nullable=True),
    sa.Column('smov_id2', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_table('search_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.String(length=255), nullable=False),
    sa.Column('user_nm', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    op.drop_table('gb_works')
    op.drop_table('gb_search_lists')
    op.drop_table('gb_mov_sim')
    op.drop_table('gb_mov')
    op.drop_table('gb_meta_sim')
    op.drop_table('gb_account')
    # ### end Alembic commands ###
