"""empty message

Revision ID: 885786a49f1f
Revises: 
Create Date: 2021-02-15 17:22:53.334988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885786a49f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gb_mov',
    sa.Column('mov_id', sa.Integer(), nullable=False),
    sa.Column('mov_prov', sa.String(length=255), nullable=True),
    sa.Column('mov_prov_id', sa.String(length=255), nullable=True),
    sa.Column('mov_title', sa.String(length=255), nullable=True),
    sa.Column('mov_owner', sa.String(length=255), nullable=True),
    sa.Column('mov_date', sa.String(length=10), nullable=True),
    sa.Column('mov_view_cnt', sa.BigInteger(), nullable=True),
    sa.Column('mov_tag', sa.Text(), nullable=True),
    sa.Column('mov_desc', sa.Text(), nullable=True),
    sa.Column('cdate', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('mov_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gb_mov')
    # ### end Alembic commands ###
